providers_list:
  googlePlus: googlePlus
  facebook: facebook
  twitter: twitter
  linkedin: linkedin
  digg: digg
  delicious: delicious
  stumbleupon: stumbleupon
  pinterest: pinterest
use_module_css: 1
use_custom_css_selector: ''
use_google_analytics_tracking: 1
providers:
  googlePlus: googlePlus
  facebook: facebook
  twitter: twitter
  linkedin: linkedin
  digg: 0
  delicious: 0
  stumbleupon: 0
  pinterest: 0
_core:
  default_config_hash: FkSYXpdtSUGUrORvIuxajnDn2UxHjMfkQDVuULmEDM4
langcode: ru
